# Generated by Django 4.2.6 on 2023-10-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid_serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('c_firstname', models.CharField(max_length=200, null=True)),
                ('c_lastname', models.CharField(max_length=200, null=True)),
                ('c_email', models.CharField(max_length=30, null=True)),
                ('c_image', models.FileField(null=True, upload_to='')),
                ('c_phoneno', models.IntegerField(null=True)),
                ('c_birthdate', models.DateField(null=True)),
                ('c_streetaddress', models.TextField(null=True)),
                ('c_city', models.CharField(max_length=100, null=True)),
                ('c_state', models.CharField(max_length=100, null=True)),
                ('c_pincode', models.IntegerField(null=True)),
                ('c_country', models.CharField(max_length=100, null=True)),
                ('request', models.CharField(max_length=15)),
            ],
        ),
    ]
