# Generated by Django 4.2.6 on 2023-10-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid_serviceapp', '0002_customer_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviceman_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('s_firstname', models.CharField(max_length=200, null=True)),
                ('s_lastname', models.CharField(max_length=200, null=True)),
                ('s_email', models.CharField(max_length=30, null=True)),
                ('s_image', models.FileField(null=True, upload_to='')),
                ('s_phoneno', models.IntegerField(null=True)),
                ('s_birthdate', models.DateField(null=True)),
                ('s_streetaddress', models.TextField(null=True)),
                ('s_city', models.CharField(max_length=100, null=True)),
                ('s_state', models.CharField(max_length=100, null=True)),
                ('s_pincode', models.IntegerField(null=True)),
                ('s_country', models.CharField(max_length=100, null=True)),
                ('action', models.CharField(max_length=15)),
            ],
        ),
    ]
