# Generated by Django 4.2.6 on 2023-11-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid_serviceapp', '0005_customer_register_c_dbooking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Service_City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer_register',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceman_register',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
