# Generated by Django 4.2.6 on 2023-11-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid_serviceapp', '0009_remove_customer_register_c_dbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_register',
            name='c_birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customer_register',
            name='c_dbooking',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='serviceman_register',
            name='s_birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='serviceman_register',
            name='s_dapp',
            field=models.DateField(null=True),
        ),
    ]
