# Generated by Django 4.2.6 on 2024-01-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid_serviceapp', '0010_customer_register_c_birthdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_username', models.CharField(max_length=30, null=True)),
                ('c_email', models.CharField(max_length=30, null=True)),
                ('c_phoneno', models.IntegerField(null=True)),
                ('s_servicemanname', models.CharField(max_length=200, null=True)),
                ('s_service', models.CharField(max_length=400, null=True)),
                ('s_scity', models.CharField(max_length=400, null=True)),
                ('serviceman_contact', models.IntegerField(null=True)),
                ('starting_date', models.DateField(null=True)),
                ('ending_date', models.DateField(null=True)),
                ('no_days', models.IntegerField(null=True)),
                ('tot_amount', models.IntegerField(null=True)),
                ('action', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='service_category',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
