# Generated by Django 4.2.6 on 2024-01-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid_serviceapp', '0011_booking_data_service_category_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_data',
            name='price_per_day',
            field=models.IntegerField(null=True),
        ),
    ]
